# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: False
  vars_prompt:
    inst_name: "What's the name of the instance?"
  tasks:

    - name: Create a series of RHEL 7.1 VMs in AWS, based on the count number listed below
      ec2:
         key_name: ansible_test
         instance_type: t2.micro
         aws_region: us-east-1
         image: "ami-12663b7a"
         wait: true
         exact_count: 1
         vpc_subnet_id: subnet-33888e09
         count_tag:
            Name: Demo
         instance_tags:
            Name: "{{inst_name}}"
            Tower: ""
      register: ec2
      register: result

    - name: Have my local computer give me a pat on the back for a job well done.
      local_action: osx_say msg="Great job Kyle! That was a really, really cool demo." voice=Victoria
      when: result|succeeded
